// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/haseebh/anchoreclient/client/archives"
	"github.com/haseebh/anchoreclient/client/events"
	"github.com/haseebh/anchoreclient/client/identity"
	"github.com/haseebh/anchoreclient/client/images"
	"github.com/haseebh/anchoreclient/client/import_operations"
	"github.com/haseebh/anchoreclient/client/operations"
	"github.com/haseebh/anchoreclient/client/policies"
	"github.com/haseebh/anchoreclient/client/queries"
	"github.com/haseebh/anchoreclient/client/registries"
	"github.com/haseebh/anchoreclient/client/repository_credentials"
	"github.com/haseebh/anchoreclient/client/subscriptions"
	"github.com/haseebh/anchoreclient/client/summaries"
	"github.com/haseebh/anchoreclient/client/system"
	"github.com/haseebh/anchoreclient/client/user_management"
	"github.com/haseebh/anchoreclient/client/vulnerabilities"
)

// Default anchore engine API server HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new anchore engine API server HTTP client.
func NewHTTPClient(formats strfmt.Registry) *AnchoreEngineAPIServer {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new anchore engine API server HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *AnchoreEngineAPIServer {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new anchore engine API server client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *AnchoreEngineAPIServer {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(AnchoreEngineAPIServer)
	cli.Transport = transport

	cli.Archives = archives.New(transport, formats)

	cli.Events = events.New(transport, formats)

	cli.Identity = identity.New(transport, formats)

	cli.Images = images.New(transport, formats)

	cli.ImportOperations = import_operations.New(transport, formats)

	cli.Operations = operations.New(transport, formats)

	cli.Policies = policies.New(transport, formats)

	cli.Queries = queries.New(transport, formats)

	cli.Registries = registries.New(transport, formats)

	cli.RepositoryCredentials = repository_credentials.New(transport, formats)

	cli.Subscriptions = subscriptions.New(transport, formats)

	cli.Summaries = summaries.New(transport, formats)

	cli.System = system.New(transport, formats)

	cli.UserManagement = user_management.New(transport, formats)

	cli.Vulnerabilities = vulnerabilities.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// AnchoreEngineAPIServer is a client for anchore engine API server
type AnchoreEngineAPIServer struct {
	Archives *archives.Client

	Events *events.Client

	Identity *identity.Client

	Images *images.Client

	ImportOperations *import_operations.Client

	Operations *operations.Client

	Policies *policies.Client

	Queries *queries.Client

	Registries *registries.Client

	RepositoryCredentials *repository_credentials.Client

	Subscriptions *subscriptions.Client

	Summaries *summaries.Client

	System *system.Client

	UserManagement *user_management.Client

	Vulnerabilities *vulnerabilities.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *AnchoreEngineAPIServer) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Archives.SetTransport(transport)

	c.Events.SetTransport(transport)

	c.Identity.SetTransport(transport)

	c.Images.SetTransport(transport)

	c.ImportOperations.SetTransport(transport)

	c.Operations.SetTransport(transport)

	c.Policies.SetTransport(transport)

	c.Queries.SetTransport(transport)

	c.Registries.SetTransport(transport)

	c.RepositoryCredentials.SetTransport(transport)

	c.Subscriptions.SetTransport(transport)

	c.Summaries.SetTransport(transport)

	c.System.SetTransport(transport)

	c.UserManagement.SetTransport(transport)

	c.Vulnerabilities.SetTransport(transport)

}
