// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetImageContentByTypeFilesParams creates a new GetImageContentByTypeFilesParams object
// with the default values initialized.
func NewGetImageContentByTypeFilesParams() *GetImageContentByTypeFilesParams {
	var ()
	return &GetImageContentByTypeFilesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetImageContentByTypeFilesParamsWithTimeout creates a new GetImageContentByTypeFilesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetImageContentByTypeFilesParamsWithTimeout(timeout time.Duration) *GetImageContentByTypeFilesParams {
	var ()
	return &GetImageContentByTypeFilesParams{

		timeout: timeout,
	}
}

// NewGetImageContentByTypeFilesParamsWithContext creates a new GetImageContentByTypeFilesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetImageContentByTypeFilesParamsWithContext(ctx context.Context) *GetImageContentByTypeFilesParams {
	var ()
	return &GetImageContentByTypeFilesParams{

		Context: ctx,
	}
}

// NewGetImageContentByTypeFilesParamsWithHTTPClient creates a new GetImageContentByTypeFilesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetImageContentByTypeFilesParamsWithHTTPClient(client *http.Client) *GetImageContentByTypeFilesParams {
	var ()
	return &GetImageContentByTypeFilesParams{
		HTTPClient: client,
	}
}

/*GetImageContentByTypeFilesParams contains all the parameters to send to the API endpoint
for the get image content by type files operation typically these are written to a http.Request
*/
type GetImageContentByTypeFilesParams struct {

	/*ImageDigest*/
	ImageDigest string
	/*XAnchoreAccount
	  An account name to change the resource scope of the request to that account, if permissions allow (admin only)

	*/
	XAnchoreAccount *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get image content by type files params
func (o *GetImageContentByTypeFilesParams) WithTimeout(timeout time.Duration) *GetImageContentByTypeFilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get image content by type files params
func (o *GetImageContentByTypeFilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get image content by type files params
func (o *GetImageContentByTypeFilesParams) WithContext(ctx context.Context) *GetImageContentByTypeFilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get image content by type files params
func (o *GetImageContentByTypeFilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get image content by type files params
func (o *GetImageContentByTypeFilesParams) WithHTTPClient(client *http.Client) *GetImageContentByTypeFilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get image content by type files params
func (o *GetImageContentByTypeFilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImageDigest adds the imageDigest to the get image content by type files params
func (o *GetImageContentByTypeFilesParams) WithImageDigest(imageDigest string) *GetImageContentByTypeFilesParams {
	o.SetImageDigest(imageDigest)
	return o
}

// SetImageDigest adds the imageDigest to the get image content by type files params
func (o *GetImageContentByTypeFilesParams) SetImageDigest(imageDigest string) {
	o.ImageDigest = imageDigest
}

// WithXAnchoreAccount adds the xAnchoreAccount to the get image content by type files params
func (o *GetImageContentByTypeFilesParams) WithXAnchoreAccount(xAnchoreAccount *string) *GetImageContentByTypeFilesParams {
	o.SetXAnchoreAccount(xAnchoreAccount)
	return o
}

// SetXAnchoreAccount adds the xAnchoreAccount to the get image content by type files params
func (o *GetImageContentByTypeFilesParams) SetXAnchoreAccount(xAnchoreAccount *string) {
	o.XAnchoreAccount = xAnchoreAccount
}

// WriteToRequest writes these params to a swagger request
func (o *GetImageContentByTypeFilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param imageDigest
	if err := r.SetPathParam("imageDigest", o.ImageDigest); err != nil {
		return err
	}

	if o.XAnchoreAccount != nil {

		// header param x-anchore-account
		if err := r.SetHeaderParam("x-anchore-account", *o.XAnchoreAccount); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
