// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListImageMetadataParams creates a new ListImageMetadataParams object
// with the default values initialized.
func NewListImageMetadataParams() *ListImageMetadataParams {
	var ()
	return &ListImageMetadataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListImageMetadataParamsWithTimeout creates a new ListImageMetadataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListImageMetadataParamsWithTimeout(timeout time.Duration) *ListImageMetadataParams {
	var ()
	return &ListImageMetadataParams{

		timeout: timeout,
	}
}

// NewListImageMetadataParamsWithContext creates a new ListImageMetadataParams object
// with the default values initialized, and the ability to set a context for a request
func NewListImageMetadataParamsWithContext(ctx context.Context) *ListImageMetadataParams {
	var ()
	return &ListImageMetadataParams{

		Context: ctx,
	}
}

// NewListImageMetadataParamsWithHTTPClient creates a new ListImageMetadataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListImageMetadataParamsWithHTTPClient(client *http.Client) *ListImageMetadataParams {
	var ()
	return &ListImageMetadataParams{
		HTTPClient: client,
	}
}

/*ListImageMetadataParams contains all the parameters to send to the API endpoint
for the list image metadata operation typically these are written to a http.Request
*/
type ListImageMetadataParams struct {

	/*ImageDigest*/
	ImageDigest string
	/*XAnchoreAccount
	  An account name to change the resource scope of the request to that account, if permissions allow (admin only)

	*/
	XAnchoreAccount *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list image metadata params
func (o *ListImageMetadataParams) WithTimeout(timeout time.Duration) *ListImageMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list image metadata params
func (o *ListImageMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list image metadata params
func (o *ListImageMetadataParams) WithContext(ctx context.Context) *ListImageMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list image metadata params
func (o *ListImageMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list image metadata params
func (o *ListImageMetadataParams) WithHTTPClient(client *http.Client) *ListImageMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list image metadata params
func (o *ListImageMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImageDigest adds the imageDigest to the list image metadata params
func (o *ListImageMetadataParams) WithImageDigest(imageDigest string) *ListImageMetadataParams {
	o.SetImageDigest(imageDigest)
	return o
}

// SetImageDigest adds the imageDigest to the list image metadata params
func (o *ListImageMetadataParams) SetImageDigest(imageDigest string) {
	o.ImageDigest = imageDigest
}

// WithXAnchoreAccount adds the xAnchoreAccount to the list image metadata params
func (o *ListImageMetadataParams) WithXAnchoreAccount(xAnchoreAccount *string) *ListImageMetadataParams {
	o.SetXAnchoreAccount(xAnchoreAccount)
	return o
}

// SetXAnchoreAccount adds the xAnchoreAccount to the list image metadata params
func (o *ListImageMetadataParams) SetXAnchoreAccount(xAnchoreAccount *string) {
	o.XAnchoreAccount = xAnchoreAccount
}

// WriteToRequest writes these params to a swagger request
func (o *ListImageMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param imageDigest
	if err := r.SetPathParam("imageDigest", o.ImageDigest); err != nil {
		return err
	}

	if o.XAnchoreAccount != nil {

		// header param x-anchore-account
		if err := r.SetHeaderParam("x-anchore-account", *o.XAnchoreAccount); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
