// Code generated by go-swagger; DO NOT EDIT.

package identity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/haseebh/anchoreclient/models"
)

// NewAddCredentialParams creates a new AddCredentialParams object
// with the default values initialized.
func NewAddCredentialParams() *AddCredentialParams {
	var ()
	return &AddCredentialParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddCredentialParamsWithTimeout creates a new AddCredentialParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddCredentialParamsWithTimeout(timeout time.Duration) *AddCredentialParams {
	var ()
	return &AddCredentialParams{

		timeout: timeout,
	}
}

// NewAddCredentialParamsWithContext creates a new AddCredentialParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddCredentialParamsWithContext(ctx context.Context) *AddCredentialParams {
	var ()
	return &AddCredentialParams{

		Context: ctx,
	}
}

// NewAddCredentialParamsWithHTTPClient creates a new AddCredentialParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddCredentialParamsWithHTTPClient(client *http.Client) *AddCredentialParams {
	var ()
	return &AddCredentialParams{
		HTTPClient: client,
	}
}

/*AddCredentialParams contains all the parameters to send to the API endpoint
for the add credential operation typically these are written to a http.Request
*/
type AddCredentialParams struct {

	/*Credential*/
	Credential *models.AccessCredential

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add credential params
func (o *AddCredentialParams) WithTimeout(timeout time.Duration) *AddCredentialParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add credential params
func (o *AddCredentialParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add credential params
func (o *AddCredentialParams) WithContext(ctx context.Context) *AddCredentialParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add credential params
func (o *AddCredentialParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add credential params
func (o *AddCredentialParams) WithHTTPClient(client *http.Client) *AddCredentialParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add credential params
func (o *AddCredentialParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCredential adds the credential to the add credential params
func (o *AddCredentialParams) WithCredential(credential *models.AccessCredential) *AddCredentialParams {
	o.SetCredential(credential)
	return o
}

// SetCredential adds the credential to the add credential params
func (o *AddCredentialParams) SetCredential(credential *models.AccessCredential) {
	o.Credential = credential
}

// WriteToRequest writes these params to a swagger request
func (o *AddCredentialParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Credential != nil {
		if err := r.SetBodyParam(o.Credential); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
