// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/haseebh/anchoreclient/models"
)

// GetSystemFeedsReader is a Reader for the GetSystemFeeds structure.
type GetSystemFeedsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSystemFeedsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSystemFeedsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetSystemFeedsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSystemFeedsOK creates a GetSystemFeedsOK with default headers values
func NewGetSystemFeedsOK() *GetSystemFeedsOK {
	return &GetSystemFeedsOK{}
}

/*GetSystemFeedsOK handles this case with default header values.

success
*/
type GetSystemFeedsOK struct {
	Payload []*models.FeedMetadata
}

func (o *GetSystemFeedsOK) Error() string {
	return fmt.Sprintf("[GET /system/feeds][%d] getSystemFeedsOK  %+v", 200, o.Payload)
}

func (o *GetSystemFeedsOK) GetPayload() []*models.FeedMetadata {
	return o.Payload
}

func (o *GetSystemFeedsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSystemFeedsInternalServerError creates a GetSystemFeedsInternalServerError with default headers values
func NewGetSystemFeedsInternalServerError() *GetSystemFeedsInternalServerError {
	return &GetSystemFeedsInternalServerError{}
}

/*GetSystemFeedsInternalServerError handles this case with default header values.

Internal Error
*/
type GetSystemFeedsInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *GetSystemFeedsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /system/feeds][%d] getSystemFeedsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetSystemFeedsInternalServerError) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *GetSystemFeedsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
