// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSystemFeedsParams creates a new GetSystemFeedsParams object
// with the default values initialized.
func NewGetSystemFeedsParams() *GetSystemFeedsParams {

	return &GetSystemFeedsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSystemFeedsParamsWithTimeout creates a new GetSystemFeedsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSystemFeedsParamsWithTimeout(timeout time.Duration) *GetSystemFeedsParams {

	return &GetSystemFeedsParams{

		timeout: timeout,
	}
}

// NewGetSystemFeedsParamsWithContext creates a new GetSystemFeedsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSystemFeedsParamsWithContext(ctx context.Context) *GetSystemFeedsParams {

	return &GetSystemFeedsParams{

		Context: ctx,
	}
}

// NewGetSystemFeedsParamsWithHTTPClient creates a new GetSystemFeedsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSystemFeedsParamsWithHTTPClient(client *http.Client) *GetSystemFeedsParams {

	return &GetSystemFeedsParams{
		HTTPClient: client,
	}
}

/*GetSystemFeedsParams contains all the parameters to send to the API endpoint
for the get system feeds operation typically these are written to a http.Request
*/
type GetSystemFeedsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get system feeds params
func (o *GetSystemFeedsParams) WithTimeout(timeout time.Duration) *GetSystemFeedsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get system feeds params
func (o *GetSystemFeedsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get system feeds params
func (o *GetSystemFeedsParams) WithContext(ctx context.Context) *GetSystemFeedsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get system feeds params
func (o *GetSystemFeedsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get system feeds params
func (o *GetSystemFeedsParams) WithHTTPClient(client *http.Client) *GetSystemFeedsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get system feeds params
func (o *GetSystemFeedsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSystemFeedsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
