// Code generated by go-swagger; DO NOT EDIT.

package archives

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/haseebh/anchoreclient/models"
)

// CreateAnalysisArchiveRuleReader is a Reader for the CreateAnalysisArchiveRule structure.
type CreateAnalysisArchiveRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAnalysisArchiveRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateAnalysisArchiveRuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewCreateAnalysisArchiveRuleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateAnalysisArchiveRuleOK creates a CreateAnalysisArchiveRuleOK with default headers values
func NewCreateAnalysisArchiveRuleOK() *CreateAnalysisArchiveRuleOK {
	return &CreateAnalysisArchiveRuleOK{}
}

/*CreateAnalysisArchiveRuleOK handles this case with default header values.

Archive transition rule
*/
type CreateAnalysisArchiveRuleOK struct {
	Payload *models.AnalysisArchiveTransitionRule
}

func (o *CreateAnalysisArchiveRuleOK) Error() string {
	return fmt.Sprintf("[POST /archives/rules][%d] createAnalysisArchiveRuleOK  %+v", 200, o.Payload)
}

func (o *CreateAnalysisArchiveRuleOK) GetPayload() *models.AnalysisArchiveTransitionRule {
	return o.Payload
}

func (o *CreateAnalysisArchiveRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AnalysisArchiveTransitionRule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAnalysisArchiveRuleInternalServerError creates a CreateAnalysisArchiveRuleInternalServerError with default headers values
func NewCreateAnalysisArchiveRuleInternalServerError() *CreateAnalysisArchiveRuleInternalServerError {
	return &CreateAnalysisArchiveRuleInternalServerError{}
}

/*CreateAnalysisArchiveRuleInternalServerError handles this case with default header values.

Internal error
*/
type CreateAnalysisArchiveRuleInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *CreateAnalysisArchiveRuleInternalServerError) Error() string {
	return fmt.Sprintf("[POST /archives/rules][%d] createAnalysisArchiveRuleInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateAnalysisArchiveRuleInternalServerError) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *CreateAnalysisArchiveRuleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
