// Code generated by go-swagger; DO NOT EDIT.

package archives

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAnalysisArchiveRuleParams creates a new DeleteAnalysisArchiveRuleParams object
// with the default values initialized.
func NewDeleteAnalysisArchiveRuleParams() *DeleteAnalysisArchiveRuleParams {
	var ()
	return &DeleteAnalysisArchiveRuleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAnalysisArchiveRuleParamsWithTimeout creates a new DeleteAnalysisArchiveRuleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAnalysisArchiveRuleParamsWithTimeout(timeout time.Duration) *DeleteAnalysisArchiveRuleParams {
	var ()
	return &DeleteAnalysisArchiveRuleParams{

		timeout: timeout,
	}
}

// NewDeleteAnalysisArchiveRuleParamsWithContext creates a new DeleteAnalysisArchiveRuleParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAnalysisArchiveRuleParamsWithContext(ctx context.Context) *DeleteAnalysisArchiveRuleParams {
	var ()
	return &DeleteAnalysisArchiveRuleParams{

		Context: ctx,
	}
}

// NewDeleteAnalysisArchiveRuleParamsWithHTTPClient creates a new DeleteAnalysisArchiveRuleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAnalysisArchiveRuleParamsWithHTTPClient(client *http.Client) *DeleteAnalysisArchiveRuleParams {
	var ()
	return &DeleteAnalysisArchiveRuleParams{
		HTTPClient: client,
	}
}

/*DeleteAnalysisArchiveRuleParams contains all the parameters to send to the API endpoint
for the delete analysis archive rule operation typically these are written to a http.Request
*/
type DeleteAnalysisArchiveRuleParams struct {

	/*RuleID*/
	RuleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete analysis archive rule params
func (o *DeleteAnalysisArchiveRuleParams) WithTimeout(timeout time.Duration) *DeleteAnalysisArchiveRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete analysis archive rule params
func (o *DeleteAnalysisArchiveRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete analysis archive rule params
func (o *DeleteAnalysisArchiveRuleParams) WithContext(ctx context.Context) *DeleteAnalysisArchiveRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete analysis archive rule params
func (o *DeleteAnalysisArchiveRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete analysis archive rule params
func (o *DeleteAnalysisArchiveRuleParams) WithHTTPClient(client *http.Client) *DeleteAnalysisArchiveRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete analysis archive rule params
func (o *DeleteAnalysisArchiveRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRuleID adds the ruleID to the delete analysis archive rule params
func (o *DeleteAnalysisArchiveRuleParams) WithRuleID(ruleID string) *DeleteAnalysisArchiveRuleParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the delete analysis archive rule params
func (o *DeleteAnalysisArchiveRuleParams) SetRuleID(ruleID string) {
	o.RuleID = ruleID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAnalysisArchiveRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ruleId
	if err := r.SetPathParam("ruleId", o.RuleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
