// Code generated by go-swagger; DO NOT EDIT.

package archives

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetArchivedAnalysisParams creates a new GetArchivedAnalysisParams object
// with the default values initialized.
func NewGetArchivedAnalysisParams() *GetArchivedAnalysisParams {
	var ()
	return &GetArchivedAnalysisParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetArchivedAnalysisParamsWithTimeout creates a new GetArchivedAnalysisParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetArchivedAnalysisParamsWithTimeout(timeout time.Duration) *GetArchivedAnalysisParams {
	var ()
	return &GetArchivedAnalysisParams{

		timeout: timeout,
	}
}

// NewGetArchivedAnalysisParamsWithContext creates a new GetArchivedAnalysisParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetArchivedAnalysisParamsWithContext(ctx context.Context) *GetArchivedAnalysisParams {
	var ()
	return &GetArchivedAnalysisParams{

		Context: ctx,
	}
}

// NewGetArchivedAnalysisParamsWithHTTPClient creates a new GetArchivedAnalysisParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetArchivedAnalysisParamsWithHTTPClient(client *http.Client) *GetArchivedAnalysisParams {
	var ()
	return &GetArchivedAnalysisParams{
		HTTPClient: client,
	}
}

/*GetArchivedAnalysisParams contains all the parameters to send to the API endpoint
for the get archived analysis operation typically these are written to a http.Request
*/
type GetArchivedAnalysisParams struct {

	/*ImageDigest
	  The image digest to identify the image analysis

	*/
	ImageDigest string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get archived analysis params
func (o *GetArchivedAnalysisParams) WithTimeout(timeout time.Duration) *GetArchivedAnalysisParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get archived analysis params
func (o *GetArchivedAnalysisParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get archived analysis params
func (o *GetArchivedAnalysisParams) WithContext(ctx context.Context) *GetArchivedAnalysisParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get archived analysis params
func (o *GetArchivedAnalysisParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get archived analysis params
func (o *GetArchivedAnalysisParams) WithHTTPClient(client *http.Client) *GetArchivedAnalysisParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get archived analysis params
func (o *GetArchivedAnalysisParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImageDigest adds the imageDigest to the get archived analysis params
func (o *GetArchivedAnalysisParams) WithImageDigest(imageDigest string) *GetArchivedAnalysisParams {
	o.SetImageDigest(imageDigest)
	return o
}

// SetImageDigest adds the imageDigest to the get archived analysis params
func (o *GetArchivedAnalysisParams) SetImageDigest(imageDigest string) {
	o.ImageDigest = imageDigest
}

// WriteToRequest writes these params to a swagger request
func (o *GetArchivedAnalysisParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param imageDigest
	if err := r.SetPathParam("imageDigest", o.ImageDigest); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
