// Code generated by go-swagger; DO NOT EDIT.

package archives

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/haseebh/anchoreclient/models"
)

// GetAnalysisArchiveRuleReader is a Reader for the GetAnalysisArchiveRule structure.
type GetAnalysisArchiveRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAnalysisArchiveRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAnalysisArchiveRuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetAnalysisArchiveRuleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAnalysisArchiveRuleOK creates a GetAnalysisArchiveRuleOK with default headers values
func NewGetAnalysisArchiveRuleOK() *GetAnalysisArchiveRuleOK {
	return &GetAnalysisArchiveRuleOK{}
}

/*GetAnalysisArchiveRuleOK handles this case with default header values.

Archive transition rule
*/
type GetAnalysisArchiveRuleOK struct {
	Payload *models.AnalysisArchiveTransitionRule
}

func (o *GetAnalysisArchiveRuleOK) Error() string {
	return fmt.Sprintf("[GET /archives/rules/{ruleId}][%d] getAnalysisArchiveRuleOK  %+v", 200, o.Payload)
}

func (o *GetAnalysisArchiveRuleOK) GetPayload() *models.AnalysisArchiveTransitionRule {
	return o.Payload
}

func (o *GetAnalysisArchiveRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AnalysisArchiveTransitionRule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAnalysisArchiveRuleInternalServerError creates a GetAnalysisArchiveRuleInternalServerError with default headers values
func NewGetAnalysisArchiveRuleInternalServerError() *GetAnalysisArchiveRuleInternalServerError {
	return &GetAnalysisArchiveRuleInternalServerError{}
}

/*GetAnalysisArchiveRuleInternalServerError handles this case with default header values.

Internal error
*/
type GetAnalysisArchiveRuleInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *GetAnalysisArchiveRuleInternalServerError) Error() string {
	return fmt.Sprintf("[GET /archives/rules/{ruleId}][%d] getAnalysisArchiveRuleInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAnalysisArchiveRuleInternalServerError) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *GetAnalysisArchiveRuleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
