// Code generated by go-swagger; DO NOT EDIT.

package archives

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/haseebh/anchoreclient/models"
)

// ListAnalysisArchiveReader is a Reader for the ListAnalysisArchive structure.
type ListAnalysisArchiveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAnalysisArchiveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListAnalysisArchiveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewListAnalysisArchiveInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListAnalysisArchiveOK creates a ListAnalysisArchiveOK with default headers values
func NewListAnalysisArchiveOK() *ListAnalysisArchiveOK {
	return &ListAnalysisArchiveOK{}
}

/*ListAnalysisArchiveOK handles this case with default header values.

Image analysis archive listing for the requesting account (not the whole system)
*/
type ListAnalysisArchiveOK struct {
	Payload models.ArchivedAnalyses
}

func (o *ListAnalysisArchiveOK) Error() string {
	return fmt.Sprintf("[GET /archives/images][%d] listAnalysisArchiveOK  %+v", 200, o.Payload)
}

func (o *ListAnalysisArchiveOK) GetPayload() models.ArchivedAnalyses {
	return o.Payload
}

func (o *ListAnalysisArchiveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAnalysisArchiveInternalServerError creates a ListAnalysisArchiveInternalServerError with default headers values
func NewListAnalysisArchiveInternalServerError() *ListAnalysisArchiveInternalServerError {
	return &ListAnalysisArchiveInternalServerError{}
}

/*ListAnalysisArchiveInternalServerError handles this case with default header values.

Internal error
*/
type ListAnalysisArchiveInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *ListAnalysisArchiveInternalServerError) Error() string {
	return fmt.Sprintf("[GET /archives/images][%d] listAnalysisArchiveInternalServerError  %+v", 500, o.Payload)
}

func (o *ListAnalysisArchiveInternalServerError) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *ListAnalysisArchiveInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
