// Code generated by go-swagger; DO NOT EDIT.

package archives

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/haseebh/anchoreclient/models"
)

// ListAnalysisArchiveRulesReader is a Reader for the ListAnalysisArchiveRules structure.
type ListAnalysisArchiveRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAnalysisArchiveRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListAnalysisArchiveRulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewListAnalysisArchiveRulesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListAnalysisArchiveRulesOK creates a ListAnalysisArchiveRulesOK with default headers values
func NewListAnalysisArchiveRulesOK() *ListAnalysisArchiveRulesOK {
	return &ListAnalysisArchiveRulesOK{}
}

/*ListAnalysisArchiveRulesOK handles this case with default header values.

Archive transition rules
*/
type ListAnalysisArchiveRulesOK struct {
	Payload models.AnalysisArchiveRules
}

func (o *ListAnalysisArchiveRulesOK) Error() string {
	return fmt.Sprintf("[GET /archives/rules][%d] listAnalysisArchiveRulesOK  %+v", 200, o.Payload)
}

func (o *ListAnalysisArchiveRulesOK) GetPayload() models.AnalysisArchiveRules {
	return o.Payload
}

func (o *ListAnalysisArchiveRulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAnalysisArchiveRulesInternalServerError creates a ListAnalysisArchiveRulesInternalServerError with default headers values
func NewListAnalysisArchiveRulesInternalServerError() *ListAnalysisArchiveRulesInternalServerError {
	return &ListAnalysisArchiveRulesInternalServerError{}
}

/*ListAnalysisArchiveRulesInternalServerError handles this case with default header values.

Internal error
*/
type ListAnalysisArchiveRulesInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *ListAnalysisArchiveRulesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /archives/rules][%d] listAnalysisArchiveRulesInternalServerError  %+v", 500, o.Payload)
}

func (o *ListAnalysisArchiveRulesInternalServerError) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *ListAnalysisArchiveRulesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
