// Code generated by go-swagger; DO NOT EDIT.

package queries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/haseebh/anchoreclient/models"
)

// QueryImagesByPackageReader is a Reader for the QueryImagesByPackage structure.
type QueryImagesByPackageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryImagesByPackageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQueryImagesByPackageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewQueryImagesByPackageBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewQueryImagesByPackageOK creates a QueryImagesByPackageOK with default headers values
func NewQueryImagesByPackageOK() *QueryImagesByPackageOK {
	return &QueryImagesByPackageOK{}
}

/*QueryImagesByPackageOK handles this case with default header values.

Image listing
*/
type QueryImagesByPackageOK struct {
	Payload *models.PaginatedImageList
}

func (o *QueryImagesByPackageOK) Error() string {
	return fmt.Sprintf("[GET /query/images/by_package][%d] queryImagesByPackageOK  %+v", 200, o.Payload)
}

func (o *QueryImagesByPackageOK) GetPayload() *models.PaginatedImageList {
	return o.Payload
}

func (o *QueryImagesByPackageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaginatedImageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryImagesByPackageBadRequest creates a QueryImagesByPackageBadRequest with default headers values
func NewQueryImagesByPackageBadRequest() *QueryImagesByPackageBadRequest {
	return &QueryImagesByPackageBadRequest{}
}

/*QueryImagesByPackageBadRequest handles this case with default header values.

Bad filter parameters
*/
type QueryImagesByPackageBadRequest struct {
	Payload *models.APIErrorResponse
}

func (o *QueryImagesByPackageBadRequest) Error() string {
	return fmt.Sprintf("[GET /query/images/by_package][%d] queryImagesByPackageBadRequest  %+v", 400, o.Payload)
}

func (o *QueryImagesByPackageBadRequest) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *QueryImagesByPackageBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
