// Code generated by go-swagger; DO NOT EDIT.

package import_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/haseebh/anchoreclient/models"
)

// ImportImageArchiveReader is a Reader for the ImportImageArchive structure.
type ImportImageArchiveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ImportImageArchiveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewImportImageArchiveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewImportImageArchiveInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewImportImageArchiveOK creates a ImportImageArchiveOK with default headers values
func NewImportImageArchiveOK() *ImportImageArchiveOK {
	return &ImportImageArchiveOK{}
}

/*ImportImageArchiveOK handles this case with default header values.

Successfully imported image to the engine
*/
type ImportImageArchiveOK struct {
	Payload models.AnchoreImageList
}

func (o *ImportImageArchiveOK) Error() string {
	return fmt.Sprintf("[POST /import/images][%d] importImageArchiveOK  %+v", 200, o.Payload)
}

func (o *ImportImageArchiveOK) GetPayload() models.AnchoreImageList {
	return o.Payload
}

func (o *ImportImageArchiveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImportImageArchiveInternalServerError creates a ImportImageArchiveInternalServerError with default headers values
func NewImportImageArchiveInternalServerError() *ImportImageArchiveInternalServerError {
	return &ImportImageArchiveInternalServerError{}
}

/*ImportImageArchiveInternalServerError handles this case with default header values.

Internal Error
*/
type ImportImageArchiveInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *ImportImageArchiveInternalServerError) Error() string {
	return fmt.Sprintf("[POST /import/images][%d] importImageArchiveInternalServerError  %+v", 500, o.Payload)
}

func (o *ImportImageArchiveInternalServerError) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *ImportImageArchiveInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
