// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOauthTokenParams creates a new GetOauthTokenParams object
// with the default values initialized.
func NewGetOauthTokenParams() *GetOauthTokenParams {

	return &GetOauthTokenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOauthTokenParamsWithTimeout creates a new GetOauthTokenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOauthTokenParamsWithTimeout(timeout time.Duration) *GetOauthTokenParams {

	return &GetOauthTokenParams{

		timeout: timeout,
	}
}

// NewGetOauthTokenParamsWithContext creates a new GetOauthTokenParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOauthTokenParamsWithContext(ctx context.Context) *GetOauthTokenParams {

	return &GetOauthTokenParams{

		Context: ctx,
	}
}

// NewGetOauthTokenParamsWithHTTPClient creates a new GetOauthTokenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOauthTokenParamsWithHTTPClient(client *http.Client) *GetOauthTokenParams {

	return &GetOauthTokenParams{
		HTTPClient: client,
	}
}

/*GetOauthTokenParams contains all the parameters to send to the API endpoint
for the get oauth token operation typically these are written to a http.Request
*/
type GetOauthTokenParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get oauth token params
func (o *GetOauthTokenParams) WithTimeout(timeout time.Duration) *GetOauthTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get oauth token params
func (o *GetOauthTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get oauth token params
func (o *GetOauthTokenParams) WithContext(ctx context.Context) *GetOauthTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get oauth token params
func (o *GetOauthTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get oauth token params
func (o *GetOauthTokenParams) WithHTTPClient(client *http.Client) *GetOauthTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get oauth token params
func (o *GetOauthTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetOauthTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
