// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/haseebh/anchoreclient/models"
)

// VersionNoopReader is a Reader for the VersionNoop structure.
type VersionNoopReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VersionNoopReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVersionNoopOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewVersionNoopOK creates a VersionNoopOK with default headers values
func NewVersionNoopOK() *VersionNoopOK {
	return &VersionNoopOK{}
}

/*VersionNoopOK handles this case with default header values.

Version object describing version state
*/
type VersionNoopOK struct {
	Payload *models.ServiceVersion
}

func (o *VersionNoopOK) Error() string {
	return fmt.Sprintf("[GET /version][%d] versionNoopOK  %+v", 200, o.Payload)
}

func (o *VersionNoopOK) GetPayload() *models.ServiceVersion {
	return o.Payload
}

func (o *VersionNoopOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceVersion)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
