// Code generated by go-swagger; DO NOT EDIT.

package events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/haseebh/anchoreclient/models"
)

// DeleteEventsReader is a Reader for the DeleteEvents structure.
type DeleteEventsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteEventsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteEventsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewDeleteEventsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteEventsOK creates a DeleteEventsOK with default headers values
func NewDeleteEventsOK() *DeleteEventsOK {
	return &DeleteEventsOK{}
}

/*DeleteEventsOK handles this case with default header values.

List of deleted event IDs
*/
type DeleteEventsOK struct {
	Payload []string
}

func (o *DeleteEventsOK) Error() string {
	return fmt.Sprintf("[DELETE /events][%d] deleteEventsOK  %+v", 200, o.Payload)
}

func (o *DeleteEventsOK) GetPayload() []string {
	return o.Payload
}

func (o *DeleteEventsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteEventsInternalServerError creates a DeleteEventsInternalServerError with default headers values
func NewDeleteEventsInternalServerError() *DeleteEventsInternalServerError {
	return &DeleteEventsInternalServerError{}
}

/*DeleteEventsInternalServerError handles this case with default header values.

Internal Error
*/
type DeleteEventsInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *DeleteEventsInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /events][%d] deleteEventsInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteEventsInternalServerError) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *DeleteEventsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
