// Code generated by go-swagger; DO NOT EDIT.

package events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetEventParams creates a new GetEventParams object
// with the default values initialized.
func NewGetEventParams() *GetEventParams {
	var ()
	return &GetEventParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetEventParamsWithTimeout creates a new GetEventParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetEventParamsWithTimeout(timeout time.Duration) *GetEventParams {
	var ()
	return &GetEventParams{

		timeout: timeout,
	}
}

// NewGetEventParamsWithContext creates a new GetEventParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetEventParamsWithContext(ctx context.Context) *GetEventParams {
	var ()
	return &GetEventParams{

		Context: ctx,
	}
}

// NewGetEventParamsWithHTTPClient creates a new GetEventParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetEventParamsWithHTTPClient(client *http.Client) *GetEventParams {
	var ()
	return &GetEventParams{
		HTTPClient: client,
	}
}

/*GetEventParams contains all the parameters to send to the API endpoint
for the get event operation typically these are written to a http.Request
*/
type GetEventParams struct {

	/*EventID
	  Event ID of the event for lookup

	*/
	EventID string
	/*XAnchoreAccount
	  An account name to change the resource scope of the request to that account, if permissions allow (admin only)

	*/
	XAnchoreAccount *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get event params
func (o *GetEventParams) WithTimeout(timeout time.Duration) *GetEventParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get event params
func (o *GetEventParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get event params
func (o *GetEventParams) WithContext(ctx context.Context) *GetEventParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get event params
func (o *GetEventParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get event params
func (o *GetEventParams) WithHTTPClient(client *http.Client) *GetEventParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get event params
func (o *GetEventParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEventID adds the eventID to the get event params
func (o *GetEventParams) WithEventID(eventID string) *GetEventParams {
	o.SetEventID(eventID)
	return o
}

// SetEventID adds the eventId to the get event params
func (o *GetEventParams) SetEventID(eventID string) {
	o.EventID = eventID
}

// WithXAnchoreAccount adds the xAnchoreAccount to the get event params
func (o *GetEventParams) WithXAnchoreAccount(xAnchoreAccount *string) *GetEventParams {
	o.SetXAnchoreAccount(xAnchoreAccount)
	return o
}

// SetXAnchoreAccount adds the xAnchoreAccount to the get event params
func (o *GetEventParams) SetXAnchoreAccount(xAnchoreAccount *string) {
	o.XAnchoreAccount = xAnchoreAccount
}

// WriteToRequest writes these params to a swagger request
func (o *GetEventParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param eventId
	if err := r.SetPathParam("eventId", o.EventID); err != nil {
		return err
	}

	if o.XAnchoreAccount != nil {

		// header param x-anchore-account
		if err := r.SetHeaderParam("x-anchore-account", *o.XAnchoreAccount); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
