// Code generated by go-swagger; DO NOT EDIT.

package events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListEventTypesParams creates a new ListEventTypesParams object
// with the default values initialized.
func NewListEventTypesParams() *ListEventTypesParams {

	return &ListEventTypesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListEventTypesParamsWithTimeout creates a new ListEventTypesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListEventTypesParamsWithTimeout(timeout time.Duration) *ListEventTypesParams {

	return &ListEventTypesParams{

		timeout: timeout,
	}
}

// NewListEventTypesParamsWithContext creates a new ListEventTypesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListEventTypesParamsWithContext(ctx context.Context) *ListEventTypesParams {

	return &ListEventTypesParams{

		Context: ctx,
	}
}

// NewListEventTypesParamsWithHTTPClient creates a new ListEventTypesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListEventTypesParamsWithHTTPClient(client *http.Client) *ListEventTypesParams {

	return &ListEventTypesParams{
		HTTPClient: client,
	}
}

/*ListEventTypesParams contains all the parameters to send to the API endpoint
for the list event types operation typically these are written to a http.Request
*/
type ListEventTypesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list event types params
func (o *ListEventTypesParams) WithTimeout(timeout time.Duration) *ListEventTypesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list event types params
func (o *ListEventTypesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list event types params
func (o *ListEventTypesParams) WithContext(ctx context.Context) *ListEventTypesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list event types params
func (o *ListEventTypesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list event types params
func (o *ListEventTypesParams) WithHTTPClient(client *http.Client) *ListEventTypesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list event types params
func (o *ListEventTypesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListEventTypesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
