// Code generated by go-swagger; DO NOT EDIT.

package user_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/haseebh/anchoreclient/models"
)

// CreateAccountReader is a Reader for the CreateAccount structure.
type CreateAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 409:
		result := NewCreateAccountConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateAccountInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateAccountOK creates a CreateAccountOK with default headers values
func NewCreateAccountOK() *CreateAccountOK {
	return &CreateAccountOK{}
}

/*CreateAccountOK handles this case with default header values.

Account Record
*/
type CreateAccountOK struct {
	Payload *models.Account
}

func (o *CreateAccountOK) Error() string {
	return fmt.Sprintf("[POST /accounts][%d] createAccountOK  %+v", 200, o.Payload)
}

func (o *CreateAccountOK) GetPayload() *models.Account {
	return o.Payload
}

func (o *CreateAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Account)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAccountConflict creates a CreateAccountConflict with default headers values
func NewCreateAccountConflict() *CreateAccountConflict {
	return &CreateAccountConflict{}
}

/*CreateAccountConflict handles this case with default header values.

Conflicting user information. User already exists.
*/
type CreateAccountConflict struct {
	Payload *models.APIErrorResponse
}

func (o *CreateAccountConflict) Error() string {
	return fmt.Sprintf("[POST /accounts][%d] createAccountConflict  %+v", 409, o.Payload)
}

func (o *CreateAccountConflict) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *CreateAccountConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAccountInternalServerError creates a CreateAccountInternalServerError with default headers values
func NewCreateAccountInternalServerError() *CreateAccountInternalServerError {
	return &CreateAccountInternalServerError{}
}

/*CreateAccountInternalServerError handles this case with default header values.

Internal error
*/
type CreateAccountInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *CreateAccountInternalServerError) Error() string {
	return fmt.Sprintf("[POST /accounts][%d] createAccountInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateAccountInternalServerError) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *CreateAccountInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
