// Code generated by go-swagger; DO NOT EDIT.

package user_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/haseebh/anchoreclient/models"
)

// NewCreateUserCredentialParams creates a new CreateUserCredentialParams object
// with the default values initialized.
func NewCreateUserCredentialParams() *CreateUserCredentialParams {
	var ()
	return &CreateUserCredentialParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateUserCredentialParamsWithTimeout creates a new CreateUserCredentialParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateUserCredentialParamsWithTimeout(timeout time.Duration) *CreateUserCredentialParams {
	var ()
	return &CreateUserCredentialParams{

		timeout: timeout,
	}
}

// NewCreateUserCredentialParamsWithContext creates a new CreateUserCredentialParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateUserCredentialParamsWithContext(ctx context.Context) *CreateUserCredentialParams {
	var ()
	return &CreateUserCredentialParams{

		Context: ctx,
	}
}

// NewCreateUserCredentialParamsWithHTTPClient creates a new CreateUserCredentialParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateUserCredentialParamsWithHTTPClient(client *http.Client) *CreateUserCredentialParams {
	var ()
	return &CreateUserCredentialParams{
		HTTPClient: client,
	}
}

/*CreateUserCredentialParams contains all the parameters to send to the API endpoint
for the create user credential operation typically these are written to a http.Request
*/
type CreateUserCredentialParams struct {

	/*Accountname*/
	Accountname string
	/*Credential*/
	Credential *models.AccessCredential
	/*Username*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create user credential params
func (o *CreateUserCredentialParams) WithTimeout(timeout time.Duration) *CreateUserCredentialParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create user credential params
func (o *CreateUserCredentialParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create user credential params
func (o *CreateUserCredentialParams) WithContext(ctx context.Context) *CreateUserCredentialParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create user credential params
func (o *CreateUserCredentialParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create user credential params
func (o *CreateUserCredentialParams) WithHTTPClient(client *http.Client) *CreateUserCredentialParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create user credential params
func (o *CreateUserCredentialParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountname adds the accountname to the create user credential params
func (o *CreateUserCredentialParams) WithAccountname(accountname string) *CreateUserCredentialParams {
	o.SetAccountname(accountname)
	return o
}

// SetAccountname adds the accountname to the create user credential params
func (o *CreateUserCredentialParams) SetAccountname(accountname string) {
	o.Accountname = accountname
}

// WithCredential adds the credential to the create user credential params
func (o *CreateUserCredentialParams) WithCredential(credential *models.AccessCredential) *CreateUserCredentialParams {
	o.SetCredential(credential)
	return o
}

// SetCredential adds the credential to the create user credential params
func (o *CreateUserCredentialParams) SetCredential(credential *models.AccessCredential) {
	o.Credential = credential
}

// WithUsername adds the username to the create user credential params
func (o *CreateUserCredentialParams) WithUsername(username string) *CreateUserCredentialParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the create user credential params
func (o *CreateUserCredentialParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *CreateUserCredentialParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountname
	if err := r.SetPathParam("accountname", o.Accountname); err != nil {
		return err
	}

	if o.Credential != nil {
		if err := r.SetBodyParam(o.Credential); err != nil {
			return err
		}
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
