// Code generated by go-swagger; DO NOT EDIT.

package user_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/haseebh/anchoreclient/models"
)

// GetAccountUserReader is a Reader for the GetAccountUser structure.
type GetAccountUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccountUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAccountUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetAccountUserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAccountUserOK creates a GetAccountUserOK with default headers values
func NewGetAccountUserOK() *GetAccountUserOK {
	return &GetAccountUserOK{}
}

/*GetAccountUserOK handles this case with default header values.

User record
*/
type GetAccountUserOK struct {
	Payload *models.User
}

func (o *GetAccountUserOK) Error() string {
	return fmt.Sprintf("[GET /accounts/{accountname}/users/{username}][%d] getAccountUserOK  %+v", 200, o.Payload)
}

func (o *GetAccountUserOK) GetPayload() *models.User {
	return o.Payload
}

func (o *GetAccountUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.User)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountUserInternalServerError creates a GetAccountUserInternalServerError with default headers values
func NewGetAccountUserInternalServerError() *GetAccountUserInternalServerError {
	return &GetAccountUserInternalServerError{}
}

/*GetAccountUserInternalServerError handles this case with default header values.

Internal error
*/
type GetAccountUserInternalServerError struct {
	Payload *models.APIErrorResponse
}

func (o *GetAccountUserInternalServerError) Error() string {
	return fmt.Sprintf("[GET /accounts/{accountname}/users/{username}][%d] getAccountUserInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAccountUserInternalServerError) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *GetAccountUserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
