// Code generated by go-swagger; DO NOT EDIT.

package user_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListUserCredentialsParams creates a new ListUserCredentialsParams object
// with the default values initialized.
func NewListUserCredentialsParams() *ListUserCredentialsParams {
	var ()
	return &ListUserCredentialsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListUserCredentialsParamsWithTimeout creates a new ListUserCredentialsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListUserCredentialsParamsWithTimeout(timeout time.Duration) *ListUserCredentialsParams {
	var ()
	return &ListUserCredentialsParams{

		timeout: timeout,
	}
}

// NewListUserCredentialsParamsWithContext creates a new ListUserCredentialsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListUserCredentialsParamsWithContext(ctx context.Context) *ListUserCredentialsParams {
	var ()
	return &ListUserCredentialsParams{

		Context: ctx,
	}
}

// NewListUserCredentialsParamsWithHTTPClient creates a new ListUserCredentialsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListUserCredentialsParamsWithHTTPClient(client *http.Client) *ListUserCredentialsParams {
	var ()
	return &ListUserCredentialsParams{
		HTTPClient: client,
	}
}

/*ListUserCredentialsParams contains all the parameters to send to the API endpoint
for the list user credentials operation typically these are written to a http.Request
*/
type ListUserCredentialsParams struct {

	/*Accountname*/
	Accountname string
	/*Username*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list user credentials params
func (o *ListUserCredentialsParams) WithTimeout(timeout time.Duration) *ListUserCredentialsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list user credentials params
func (o *ListUserCredentialsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list user credentials params
func (o *ListUserCredentialsParams) WithContext(ctx context.Context) *ListUserCredentialsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list user credentials params
func (o *ListUserCredentialsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list user credentials params
func (o *ListUserCredentialsParams) WithHTTPClient(client *http.Client) *ListUserCredentialsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list user credentials params
func (o *ListUserCredentialsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountname adds the accountname to the list user credentials params
func (o *ListUserCredentialsParams) WithAccountname(accountname string) *ListUserCredentialsParams {
	o.SetAccountname(accountname)
	return o
}

// SetAccountname adds the accountname to the list user credentials params
func (o *ListUserCredentialsParams) SetAccountname(accountname string) {
	o.Accountname = accountname
}

// WithUsername adds the username to the list user credentials params
func (o *ListUserCredentialsParams) WithUsername(username string) *ListUserCredentialsParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the list user credentials params
func (o *ListUserCredentialsParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *ListUserCredentialsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountname
	if err := r.SetPathParam("accountname", o.Accountname); err != nil {
		return err
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
