// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AccessCredential A login credential mapped to a user identity. For password credentials, the username to present for Basic auth is the user's username from the user record
// swagger:model AccessCredential
type AccessCredential struct {

	// The timestamp of creation of the credential
	CreatedAt string `json:"created_at,omitempty"`

	// The type of credential
	// Required: true
	// Enum: [password]
	Type *string `json:"type"`

	// The credential value (e.g. the password)
	// Required: true
	Value *string `json:"value"`
}

// Validate validates this access credential
func (m *AccessCredential) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var accessCredentialTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["password"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		accessCredentialTypeTypePropEnum = append(accessCredentialTypeTypePropEnum, v)
	}
}

const (

	// AccessCredentialTypePassword captures enum value "password"
	AccessCredentialTypePassword string = "password"
)

// prop value enum
func (m *AccessCredential) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, accessCredentialTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *AccessCredential) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

func (m *AccessCredential) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AccessCredential) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccessCredential) UnmarshalBinary(b []byte) error {
	var res AccessCredential
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
