// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AnalysisArchiveSource An image reference in the analysis archive for the purposes of loading analysis from the archive into th working set
// swagger:model AnalysisArchiveSource
type AnalysisArchiveSource struct {

	// The image digest identify the analysis. Archived analyses are based on digest, tag records are restored as analysis is restored.
	Digest string `json:"digest,omitempty"`
}

// Validate validates this analysis archive source
func (m *AnalysisArchiveSource) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AnalysisArchiveSource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AnalysisArchiveSource) UnmarshalBinary(b []byte) error {
	var res AnalysisArchiveSource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
