// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ContentFilesResponse File content listings from images
// swagger:model ContentFilesResponse
type ContentFilesResponse struct {

	// content
	Content []*ContentFilesResponseContentItems0 `json:"content"`

	// content type
	ContentType string `json:"content_type,omitempty"`

	// image digest
	ImageDigest string `json:"imageDigest,omitempty"`
}

// Validate validates this content files response
func (m *ContentFilesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContent(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContentFilesResponse) validateContent(formats strfmt.Registry) error {

	if swag.IsZero(m.Content) { // not required
		return nil
	}

	for i := 0; i < len(m.Content); i++ {
		if swag.IsZero(m.Content[i]) { // not required
			continue
		}

		if m.Content[i] != nil {
			if err := m.Content[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("content" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ContentFilesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContentFilesResponse) UnmarshalBinary(b []byte) error {
	var res ContentFilesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ContentFilesResponseContentItems0 content files response content items0
// swagger:model ContentFilesResponseContentItems0
type ContentFilesResponseContentItems0 struct {

	// filename
	Filename string `json:"filename,omitempty"`

	// gid
	Gid int64 `json:"gid,omitempty"`

	// linkdest
	Linkdest *string `json:"linkdest,omitempty"`

	// mode
	Mode string `json:"mode,omitempty"`

	// sha256
	Sha256 *string `json:"sha256,omitempty"`

	// size
	Size int64 `json:"size,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// uid
	UID int64 `json:"uid,omitempty"`
}

// Validate validates this content files response content items0
func (m *ContentFilesResponseContentItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ContentFilesResponseContentItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContentFilesResponseContentItems0) UnmarshalBinary(b []byte) error {
	var res ContentFilesResponseContentItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
