// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// EventDescription A description of an event type
// swagger:model EventDescription
type EventDescription struct {

	// The message associated with the event type
	Message string `json:"message,omitempty"`

	// The event type. The last component of the fully-qualified event_type (category.subcategory.event)
	Name string `json:"name,omitempty"`

	// The type of resource this event is generated from
	ResourceType string `json:"resource_type,omitempty"`

	// The fully qualified event type as would be seen in the event payload
	Type string `json:"type,omitempty"`
}

// Validate validates this event description
func (m *EventDescription) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EventDescription) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventDescription) UnmarshalBinary(b []byte) error {
	var res EventDescription
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
