// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ImageAnalysisRequest A request to add an image to be watched and analyzed by the engine. Optionally include the dockerfile content. Either source, digest or tag must be present.
// swagger:model ImageAnalysisRequest
type ImageAnalysisRequest struct {

	// Annotations to be associated with the added image in key/value form
	Annotations interface{} `json:"annotations,omitempty"`

	// Optional override of the image creation time, only honored when both tag and digest are also supplied  e.g. 2018-10-17T18:14:00Z. Deprecated in favor of the 'source' field
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// A digest string for an image, maybe a pull string or just a digest. e.g. nginx@sha256:123 or sha256:abc123. If a pull string, it must have same regisry/repo as the tag field. Deprecated in favor of the 'source' field
	Digest string `json:"digest,omitempty"`

	// Base64 encoded content of the dockerfile for the image, if available. Deprecated in favor of the 'source' field.
	// Pattern: ^[a-zA-Z0-9+/=]+$
	Dockerfile string `json:"dockerfile,omitempty"`

	// Optional. The type of image this is adding, defaults to "docker". This can be ommitted until multiple image types are supported.
	ImageType string `json:"image_type,omitempty"`

	// source
	Source *ImageSource `json:"source,omitempty"`

	// Full pullable tag reference for image. e.g. docker.io/nginx:latest. Deprecated in favor of the 'source' field
	Tag string `json:"tag,omitempty"`
}

// Validate validates this image analysis request
func (m *ImageAnalysisRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDockerfile(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSource(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImageAnalysisRequest) validateCreatedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ImageAnalysisRequest) validateDockerfile(formats strfmt.Registry) error {

	if swag.IsZero(m.Dockerfile) { // not required
		return nil
	}

	if err := validate.Pattern("dockerfile", "body", string(m.Dockerfile), `^[a-zA-Z0-9+/=]+$`); err != nil {
		return err
	}

	return nil
}

func (m *ImageAnalysisRequest) validateSource(formats strfmt.Registry) error {

	if swag.IsZero(m.Source) { // not required
		return nil
	}

	if m.Source != nil {
		if err := m.Source.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("source")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImageAnalysisRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageAnalysisRequest) UnmarshalBinary(b []byte) error {
	var res ImageAnalysisRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
