// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ImageReference A summary of an image identity, including digest, id (if available), and any tags known to have ever been mapped to the digest
// swagger:model ImageReference
type ImageReference struct {

	// Timestamp, in rfc3339 format, indicating when the image state became 'analyzed' in Anchore Engine.
	AnalyzedAt string `json:"analyzed_at,omitempty"`

	// The image digest
	Digest string `json:"digest,omitempty"`

	// The image id if available
	ID string `json:"id,omitempty"`

	// tag history
	TagHistory []*TagEntry `json:"tag_history"`
}

// Validate validates this image reference
func (m *ImageReference) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTagHistory(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImageReference) validateTagHistory(formats strfmt.Registry) error {

	if swag.IsZero(m.TagHistory) { // not required
		return nil
	}

	for i := 0; i < len(m.TagHistory); i++ {
		if swag.IsZero(m.TagHistory[i]) { // not required
			continue
		}

		if m.TagHistory[i] != nil {
			if err := m.TagHistory[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tag_history" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImageReference) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageReference) UnmarshalBinary(b []byte) error {
	var res ImageReference
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
