// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PackageReference A record of a software item which is vulnerable or carries a fix for a vulnerability
// swagger:model PackageReference
type PackageReference struct {

	// Package name
	Name string `json:"name,omitempty"`

	// Package type (e.g. package, rpm, deb, apk, jar, npm, gem, ...)
	Type string `json:"type,omitempty"`

	// A version for the package. If null, then references all versions
	Version *string `json:"version,omitempty"`
}

// Validate validates this package reference
func (m *PackageReference) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PackageReference) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PackageReference) UnmarshalBinary(b []byte) error {
	var res PackageReference
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
