// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PolicyRule A rule that defines and decision value if the match is found true for a given image.
// swagger:model PolicyRule
type PolicyRule struct {

	// action
	// Required: true
	// Enum: [GO STOP WARN]
	Action interface{} `json:"action"`

	// gate
	// Required: true
	Gate *string `json:"gate"`

	// id
	ID string `json:"id,omitempty"`

	// params
	Params []*PolicyRuleParamsItems0 `json:"params"`

	// trigger
	// Required: true
	Trigger *string `json:"trigger"`
}

// Validate validates this policy rule
func (m *PolicyRule) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParams(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTrigger(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var policyRuleTypeActionPropEnum []interface{}

func init() {
	var res []interface{}
	if err := json.Unmarshal([]byte(`["GO","STOP","WARN"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		policyRuleTypeActionPropEnum = append(policyRuleTypeActionPropEnum, v)
	}
}

// prop value enum
func (m *PolicyRule) validateActionEnum(path, location string, value interface{}) error {
	if err := validate.Enum(path, location, value, policyRuleTypeActionPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *PolicyRule) validateAction(formats strfmt.Registry) error {

	if err := validate.Required("action", "body", m.Action); err != nil {
		return err
	}

	return nil
}

func (m *PolicyRule) validateGate(formats strfmt.Registry) error {

	if err := validate.Required("gate", "body", m.Gate); err != nil {
		return err
	}

	return nil
}

func (m *PolicyRule) validateParams(formats strfmt.Registry) error {

	if swag.IsZero(m.Params) { // not required
		return nil
	}

	for i := 0; i < len(m.Params); i++ {
		if swag.IsZero(m.Params[i]) { // not required
			continue
		}

		if m.Params[i] != nil {
			if err := m.Params[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("params" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *PolicyRule) validateTrigger(formats strfmt.Registry) error {

	if err := validate.Required("trigger", "body", m.Trigger); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PolicyRule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PolicyRule) UnmarshalBinary(b []byte) error {
	var res PolicyRule
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PolicyRuleParamsItems0 policy rule params items0
// swagger:model PolicyRuleParamsItems0
type PolicyRuleParamsItems0 struct {

	// name
	// Required: true
	Name *string `json:"name"`

	// value
	// Required: true
	Value *string `json:"value"`
}

// Validate validates this policy rule params items0
func (m *PolicyRuleParamsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PolicyRuleParamsItems0) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *PolicyRuleParamsItems0) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PolicyRuleParamsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PolicyRuleParamsItems0) UnmarshalBinary(b []byte) error {
	var res PolicyRuleParamsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
