// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RegexContentMatch Match of a named regex on a file
// swagger:model RegexContentMatch
type RegexContentMatch struct {

	// A list of line numbers in the file that matched the regex
	Lines []int64 `json:"lines"`

	// The name associated with the regular expression
	Name string `json:"name,omitempty"`

	// The regular expression used for the match
	Regex string `json:"regex,omitempty"`
}

// Validate validates this regex content match
func (m *RegexContentMatch) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegexContentMatch) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegexContentMatch) UnmarshalBinary(b []byte) error {
	var res RegexContentMatch
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
