// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RegistryTagSource An image reference using a tag in a registry, this is the most common source type.
// swagger:model RegistryTagSource
type RegistryTagSource struct {

	// Content of the dockerfile used to build the image, if available.
	Dockerfile string `json:"dockerfile,omitempty"`

	// A docker pull string (e.g. docker.io/nginx:latest, or docker.io/nginx@sha256:abd) to retrieve the image
	Pullstring string `json:"pullstring,omitempty"`
}

// Validate validates this registry tag source
func (m *RegistryTagSource) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegistryTagSource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegistryTagSource) UnmarshalBinary(b []byte) error {
	var res RegistryTagSource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
