// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RegistryConfigurationRequest A registry record describing the endpoint and credentials for a registry
// swagger:model RegistryConfigurationRequest
type RegistryConfigurationRequest struct {

	// hostname:port string for accessing the registry, as would be used in a docker pull operation. May include some or all of a repository and wildcards (e.g. docker.io/library/* or gcr.io/myproject/myrepository)
	Registry string `json:"registry,omitempty"`

	// human readable name associated with registry record
	RegistryName string `json:"registry_name,omitempty"`

	// Password portion of credential to use for this registry
	RegistryPass string `json:"registry_pass,omitempty"`

	// Type of registry
	RegistryType string `json:"registry_type,omitempty"`

	// Username portion of credential to use for this registry
	RegistryUser string `json:"registry_user,omitempty"`

	// Use TLS/SSL verification for the registry URL
	RegistryVerify bool `json:"registry_verify,omitempty"`
}

// Validate validates this registry configuration request
func (m *RegistryConfigurationRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegistryConfigurationRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegistryConfigurationRequest) UnmarshalBinary(b []byte) error {
	var res RegistryConfigurationRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
