// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// VendorDataObject vendor data object
// swagger:model VendorDataObject
type VendorDataObject struct {

	// cvss v2
	CvssV2 *CVSSV2Scores `json:"cvss_v2,omitempty"`

	// cvss v3
	CvssV3 *CVSSV3Scores `json:"cvss_v3,omitempty"`

	// Vendor Vulnerability ID
	ID string `json:"id,omitempty"`
}

// Validate validates this vendor data object
func (m *VendorDataObject) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCvssV2(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCvssV3(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VendorDataObject) validateCvssV2(formats strfmt.Registry) error {

	if swag.IsZero(m.CvssV2) { // not required
		return nil
	}

	if m.CvssV2 != nil {
		if err := m.CvssV2.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cvss_v2")
			}
			return err
		}
	}

	return nil
}

func (m *VendorDataObject) validateCvssV3(formats strfmt.Registry) error {

	if swag.IsZero(m.CvssV3) { // not required
		return nil
	}

	if m.CvssV3 != nil {
		if err := m.CvssV3.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cvss_v3")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VendorDataObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VendorDataObject) UnmarshalBinary(b []byte) error {
	var res VendorDataObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
