// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// VulnerablePackageReference A record of a software item which is vulnerable or carries a fix for a vulnerability
// swagger:model VulnerablePackageReference
type VulnerablePackageReference struct {

	// Package name
	Name string `json:"name,omitempty"`

	// Vulnerability namespace of affected package
	Namespace string `json:"namespace,omitempty"`

	// Severity of vulnerability affecting package
	Severity string `json:"severity,omitempty"`

	// Package type (e.g. package, rpm, deb, apk, jar, npm, gem, ...)
	Type string `json:"type,omitempty"`

	// A version for the package. If null, then references all versions
	Version *string `json:"version,omitempty"`
}

// Validate validates this vulnerable package reference
func (m *VulnerablePackageReference) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VulnerablePackageReference) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VulnerablePackageReference) UnmarshalBinary(b []byte) error {
	var res VulnerablePackageReference
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
